name: Microservice CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref == 'refs/heads/main' && secrets.AZURE_WEBAPP_NAME_PRO || secrets.AZURE_WEBAPP_NAME_PRE }}
          package: src
